[package]
name = "dlc"
edition = "2021"

[dependencies]
futures = "0.3"
tokio = {version = "1.39", features = ["full"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
log = "0"
env_logger = "0"

disposables_protocol = {path = "../protocol"}

