[package]
name = "dlc"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
tokio = {version = "1.39", features = ["full"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"

disposables_protocol = {path = "../protocol"}

