[package]
name = "disposables"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1"
thiserror = "1"
log = "0.4.22"

disposables_protocol = {path = "../protocol"}

[dev-dependencies]
env_logger = "0.11.5"
