#Build
name: Test
on: [push, pull_request]
env: 
  DISPOSABLES_DLC_IMAGE: dlc
jobs:
  build_dlc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - run: buildah build -t dlc .
      - run: buildah push dlc oci-archive:dlc.tar:dlc
      - uses: actions/upload-artifact@v4
        with:
          name: dlc-image
          path: dlc.tar
  rust:
    needs: [build_dlc]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dlc-image
      - run: cargo test -p disposables --lib
      - run: buildah pull oci-archive:dlc.tar
      - run: buildah images
      - run: cargo test -p test-suite
        env: 
          RUST_LOG: test_suite=debug
      - run: buildah push dlc docker-archive:dlc-docker.tar:dlc
      - run: docker load < dlc-docker.tar
      - run: docker image ls
      - run: cargo test -p test-suite
        env: 
          RUST_LOG: test_suite=debug
          DISPOSABLES_ENGINE: docker
      - run: cargo test -p disposables
  java:
    needs: [build_dlc]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dlc-image
      - run: buildah pull oci-archive:dlc.tar
      - run: buildah images
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - run: cd java && ./gradlew test
      - run: buildah push dlc docker-archive:dlc-docker.tar:dlc
      - run: docker load < dlc-docker.tar
      - run: docker image ls
      - run: cd java && ./gradlew clean test
        env: 
          DISPOSABLES_ENGINE: docker
  release_dlc:
    needs: [build_dlc, rust]
    if: ${{ startsWith(github.ref, 'refs/tags/r') }}
    env: 
      REGISTRY: ${{ vars.DLC_REGISTRY }}
      IMAGE: ${{ vars.DLC_IMAGE }}
      TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      TAG: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - run: ./dev/do_release.sh check "${TAG#r}"
      - run: buildah login -u akashrawal --password-stdin $REGISTRY <<< "$TOKEN"
      - run: buildah manifest create dlc
      - run: buildah build --arch amd64 --manifest dlc .
      - run: buildah build --arch arm64 --manifest dlc .
      - run: buildah manifest push --all dlc "docker://$IMAGE"
      - run: buildah manifest push --all dlc
             "docker://$IMAGE:`sed -e 's/r\(.*\..*\..*\)/\1/' <<< "$TAG"`"
      - run: buildah manifest push --all dlc
             "docker://$IMAGE:`sed -e 's/r\(.*\..*\)\..*/\1/' <<< "$TAG"`"
      - run: buildah manifest push --all dlc
             "docker://$IMAGE:`sed -e 's/r\(.*\)\..*\..*/\1/' <<< "$TAG"`"
  release_rust:
    needs: [release_dlc]
    if: ${{ startsWith(github.ref, 'refs/tags/r') }}
    env: 
      TAG: ${{ github.ref_name }}
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish -p disposables_protocol
      - run: cargo publish -p disposables
  release_java:
    needs: [java]
    env: 
      TAG: ${{ github.ref_name }}
      JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
      JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dlc-image
      - run: buildah pull oci-archive:dlc.tar
      - run: buildah images
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - run: cd java && ./gradlew jreleaserFullRelease
