#Build
name: Test
on: [push, pull_request]
env: 
  DISPOSABLES_DLC_IMAGE: dlc
jobs:
  build_dlc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: buildah build -t dlc .
      - run: buildah push dlc oci-archive:dlc.tar:dlc
      - uses: actions/upload-artifact@v4
        with:
          name: dlc-image
          path: dlc.tar
  rust:
    needs: [build_dlc]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dlc-image
      - run: buildah pull oci-archive:dlc.tar
      - run: buildah images
      - run: cargo test -p disposables
      - run: buildah push dlc docker-archive:dlc-docker.tar:dlc
      - run: docker load < dlc-docker.tar
      - run: docker image ls
      - run: cargo test -p disposables
        env: 
          DISPOSABLES_ENGINE: docker
  release_dlc:
    needs: [build_dlc, rust]
    if: ${{ ! startsWith(github.ref, 'refs/tags/r') }}
    env: 
      REGISTRY: ${{ vars.DLC_REGISTRY }}
      IMAGE: ${{ vars.DLC_IMAGE }}
      TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      TAG: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dlc-image
      - run: buildah login -u akashrawal --password-stdin $REGISTRY <<< "$TOKEN"
      - run: buildah pull oci-archive:dlc.tar
      - run: buildah images
      - run: buildah push dlc $IMAGE:`sed -e 's/r\(.*\..*\..*\)/\1/' <<< "$TAG"`
      - run: buildah push dlc $IMAGE:`sed -e 's/r\(.*\..*\)\..*/\1/' <<< "$TAG"`
      - run: buildah push dlc $IMAGE:`sed -e 's/r\(.*\)\..*\..*/\1/' <<< "$TAG"`
  release_rust:
    needs: [release_dlc]
    if: ${{ ! startsWith(github.ref, 'refs/tags/r') }}
    env: 
      TAG: ${{ github.ref_name }}
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish -p disposables_protocol
      - run: cargo publish -p disposables
